openapi: 3.0.1
info:
  version: 1.0.0
  title: Course Slot Booking System
  description: Endpoints for Course Slot Booking System
servers:
  - url: /api/v1
tags:
  - name: Courses
    description: Course Slot Booking endpoints

paths:
  /courses:
    get:
      tags:
        - Courses
      summary: Get all courses
      description: Fetch all courses
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCoursesResponse"
  /courses/{course}:
    get:
      tags:
        - Courses
      parameters:
        - name: course
          in: path
          required: true
          description: The name of the course to retrieve
          schema:
            type: string
      summary: Get a course by name
      description: Fetch a course by name
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GetCourseByNameResponse"
  /courses/addCourse:
    post:
      tags:
        - Courses
      summary: Add a course
      description: Add a new course
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/AddCourseRequest"
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
  /courses/book/{course}:
    put:
      tags:
        - Courses
      parameters:
        - name: course
          in: path
          required: true
          description: The name of the course to book
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookCourseRequest"
      summary: Book a course
      description: Book a slot for a course
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"
  /courses/cancel/{course}:
    put:
      tags:
        - Courses
      parameters:
        - name: course
          in: path
          required: true
          description: The name of the course to book
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookCourseRequest"
      summary: Cancel a course
      description: Cancel a slot for a course
      responses:
        200:
          description: Success
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessResponse"

components:
  schemas:
    GetCoursesResponse:
      type: object
      properties:
        courses:
          type: array
          items:
            type: object
            properties:
              id:
                type: string
              courseName:
                type: string
              capacity:
                type: number
              startTime:
                type: number
              bookedSlots:
                type: array
                items:
                  type: string
              waitingList:
                type: array
                items:
                  type: string
    GetCourseByNameResponse:
      type: object
      properties:
        id:
          type: string
        courseName:
          type: string
        capacity:
          type: number
        startTime:
          type: number
        bookedSlots:
          type: array
          items:
            type: string
        waitingList:
          type: array
          items:
            type: string
    AddCourseRequest:
      type: object
      required:
        - courseName
        - capacity
      properties:
        courseName:
          type: string
        capacity:
          type: number
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
    BookCourseRequest:
      type: object
      required:
        - userName
      properties:
        userName:
          type: string
